var style_tag = document.createElement('style');
var white_style = '#s_main, .s-top-nav, .s-hotsearch-wrapper, #content_right{display:none;} #container #content_left{width:1000px !important;} @media screen and (min-width: 1921px){#container.sam_newgrid{padding-left:0 !important; width:1000px !important;} .wrapper_new #s_tab.s_tab .s_tab_inner{padding-left:0 !important; margin-left:-36px;} .wrapper_new #head .s_form:not(div#s_fm.s_form), .s-isindex-wrap{margin-left:-60px !important;} .wrapper_new #s_tab, #page > div, #ent_sug{width:1000px !important;} .foot-container_2X1Nt div{width:1000px !important;}} .new-pmd.c-container, #container #content_left .result-op, #container #content_left .result{width:980px !important;} .new-pmd .c-span12{width:970px !important;} .new-pmd .c-span9{width:820px !important;} #container .c-container h3.t > a:first-child, #container .c-container h3.t > a:first-child em, #container .c-container .c-title > a:first-child, #container .c-container .c-title > a:first-child em{text-decoration:none !important; line-height:1.3 !important} .nums, .new_search_tool_conter{width:1000px !important;} #container.sam_newgrid{margin-left:unset !important; margin:0 auto !important;} #container #content_left .result-op, #container #content_left .result{border-radius:10px !important; box-shadow:0 0 6px #eeeeff; border-left:1px solid #eeeeee; padding:10px 10px 15px 20px !important; transition:margin-bottom 0.6s, padding-bottom 0.6s, box-shadow 0.6s;} #container #content_left .result-op:hover, #container #content_left .result:hover{box-shadow:1px 1px 10px #cccccc; border-radius:0;} .new-pmd .c-border{box-shadow:unset !important} .wrapper_new #s_tab, #page > div, #ent_sug{padding-left:0 !important; width:1080px; margin:0 auto !important;} #ent_sug{margin-top:140px !important;} #help{display:block; width:1080px; margin:0 auto; float:unset !important; padding-left:unset !important;} #head .head_wrapper{width:1080px; margin:0 auto !important;} .wrapper_new #head .s_form:not(div#s_fm.s_form), .s-isindex-wrap{margin-left:-128px;} .wrapper_new #head .s_form{padding-left:0 !important;} .slowmsg1{left:400px !important; top:120px !important; box-shadow:none !important; border:none !important; background:none !important;} div[class^="re-box_"]{box-shadow:none !important;}';
style_tag.innerHTML = white_style;
document.head.appendChild(style_tag);
document.addEventListener("DOMContentLoaded", kill_baidu_ad);
function kill_baidu_ad() {
    unsafeWindow.$(document).ajaxSuccess(function (e, xhr, opt) { // Microsoft Edge 和 Safari 不支持 $(document).ajaxSuccess()
        document.head.appendChild(style_tag);
        // $('#content_left>div').has('span:contains("广告")').remove();
        // setTimeout(function () { $('.c-container').has('.f13>span:contains("广告")').remove(); }, 2100); // 去除顽固性的延迟加载广告，一般延迟2秒左右。例如搜索“淘宝”，当页面加载完毕之后在搜索结果最前或最后会再插入一个广告。
    });
    $("#head_wrapper").addClass("s-ps-islite"); // 登录了账号之后首页有可能出现资讯信息流，以下强制关闭。
    if (document.getElementsByClassName("hide-feed").length) { $("#s-user-setting-menu .show-feed:first").css("display", "none"); setTimeout(function () { document.getElementsByClassName("hide-feed")[0].click(); }, 1000); } // 不允许开启资讯信息流，原生click()才可以实现
    if (document.getElementsByClassName("set-hide").length) { setTimeout(function () { document.getElementsByClassName("set-hide")[0].click(); $("#s-user-setting-menu .set-show:first").css("display", "none"); }, 1000); } // 关闭热榜
}

